apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: rafay-core
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: "change-me-use-openssl-rand-hex-32"
  DB_POSTGRESDB_PASSWORD: "admindbpassword"
